FROM node:18-alpine

WORKDIR /app

# Instalar dependencias
COPY package*.json ./
RUN npm ci

# Copiar el código fuente
COPY . .

# Puerto para desarrollo (opcional)
EXPOSE 3000

CMD ["npm", "run", "test"]
